on:
  schedule: 
    - cron:  "50 3,15,19 * * *" 
  workflow_dispatch:
  
name: update-puntov-tables

jobs:
  run-r-script:
    runs-on: ubuntu-latest # use Ubuntu
    env:
      ESGAMAN_MAIL: ${{ secrets.ESGAMAN_MAIL }}
      ESGAMAN_PWD: ${{ secrets.ESGAMAN_PWD }}
      BIGQUERY_ENCRYPTED_KEY: ${{ secrets.BIGQUERY_ENCRYPTED_KEY }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-renv@v2

      - name: Execute Script
        run: |
          Rscript "scripts/update_tables.R"
