on:
  schedule: 
    - cron:  "0 0,12,4 * * *" 
  workflow_dispatch:
  
name: update-puntov-tables

jobs:
  run-r-script:
    runs-on: ubuntu-latest # use Ubuntu
    env:
      # The GitHub token will be available 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} 
    steps:
      # imports an action from another repository, 
      # that enables the machine
      # to access the code inside our repository
      - uses: actions/checkout@v4
      # imports an action from another repository, 
      # that installs R on the machine
      - uses: r-lib/actions/setup-r@v2
        with:
          # uses the RStudio Package Manager
          use-public-rspm: true
      - uses: r-lib/actions/setup-renv@v2

      - name: Execute Script
        run: |
          Rscript "scripts/update_tables.R"