on:
  schedule: 
    - cron:  "24 3,12,15,22 * * *" # 12pm 9am 12am 7pm
    - cron:  "20 18,19 * * *" # 2.20pm 3.20pm
  workflow_dispatch:
  
name: update-epay-tables

jobs:
  run-r-script:
    runs-on: ubuntu-latest # use Ubuntu
    env:
      BIGQUERY_ENCRYPTED_KEY: ${{ secrets.BIGQUERY_ENCRYPTED_KEY }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-renv@v2

      - name: Execute Script
        run: |
          Rscript "scripts/update_epay.R"
